let PORT = 5000
let CONNECTION_DATABASE_STRING = 'mongodb://127.0.0.1/Wild-Life'
let JSON_SECRET_KEY = 'ASF23FGFDSG43DS128'
let COOKIE_NAME = 'jsonWebToken'

module.exports = {
    PORT,
    CONNECTION_DATABASE_STRING,
    JSON_SECRET_KEY,
    COOKIE_NAME
}